[check]
command:/usr/local/opnsense/scripts/autowol/autowol.py --action check
parameters:
type:script_output
message:AutoWoL: Check hosts status and send WoL if offline
description:AutoWoL: Monitor hosts & Auto-Wake

[wake]
command:/usr/local/opnsense/scripts/autowol/autowol.py --action wake --host-arg %s
parameters:%s
type:script_output
message:AutoWoL: Wake host
description:AutoWoL: Wake specified host

[status]
command:/usr/local/opnsense/scripts/autowol/autowol.py --action status
parameters:
type:script_output
message:AutoWoL: Get status of monitored hosts
description:AutoWoL: Show hosts status

[testalert]
command:/usr/local/opnsense/scripts/autowol/autowol.py --action test-alert --channel %s
parameters:%s
type:script_output
message:AutoWoL: Send test alert on %s
description:AutoWoL: Send test alert

[reconfigure]
command:/usr/sbin/service cron restart; echo "OK"
parameters:
type:script_output
message:AutoWoL: Reconfigured templates and cron
description:AutoWoL: Reconfigure

[logs]
command:/usr/bin/tail -n 250 /var/log/autowol.log 2>/dev/null || echo "Nenhum log registrado ainda em /var/log/autowol.log."
parameters:
type:script_output
message:AutoWoL: View recent logs
description:AutoWoL: View logs

[clearlogs]
command:/bin/cat /dev/null > /var/log/autowol.log 2>/dev/null && echo "OK"
parameters:
type:script_output
message:AutoWoL: Clear logs
description:AutoWoL: Clear logs
